name: 'Deployment'

# Only trigger, when the build workflow succeeded
on:
  pull_request:
    branches: [ main ]
    
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
          
    # Checkout the repository to the GitHub Actions runner      
    - uses: actions/checkout@v1  
      with:
        repository: AltaPay/plugin-infrastructure
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: 'origin/main'

    # Install version 0.14.4 of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init 
      working-directory: ../plugin-infrastructure/provision/plugins


    # Select a terraofrm workspace
    - name: Terraform workspace
      run: terraform workspace select magento24x
      working-directory: ../plugin-infrastructure/provision/plugins
      
      
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: ../plugin-infrastructure/provision/plugins

    # Run Terraform Apply      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ../plugin-infrastructure/provision/plugins
   
    # Run Ansible playbook
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: magento2-4-x.yml
        directory: ../plugin-infrastructure/deploy/plugins
        key: ${{secrets.SSHKEY}}
        options: |
          -u ubuntu
          -i inventory
